import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SessionAuthProvider from "@/context/SessionAuthProvider";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Quickbet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` bg-[#757575] antialiased`}
      >
        <SessionAuthProvider>
          <Header/>
          {children}
          </SessionAuthProvider>
      </body>
    </html>
  );
}
